name: No checks
on:
  pull_request:
    branches:
      - main
      - release/*
    paths:
      - "**"
      - "!**/*.ts"
      - "!**/*.tsx"
      - "!package.json"

jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to typecheck"

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to lint"

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to test"

  performance-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to performance test"
